spring:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/  # eureka server 위치 설정

management:
  endpoints:
    web:

      exposure:
        include: '*'
server:
  port: 8085
